# Asus 620 Makefile

#CFLAGS += -Idrivers/pcmcia

obj-$(CONFIG_MACH_A620)		+= asus620.o asus620_gpo.o a620_leds.o asus620_ts.o
# a620_bt_power.o

#obj-$(CONFIG_MACH_A620)         += asus620.o asus620_gpo.o asus620_lcd.o asus620_ts.o asus620_buttons.o

# generic.o
# asus620_flashfake.o
#obj-$(CONFIG_A620_LCD)          += asus620_lcd.o
#obj-$(CONFIG_A620_TS)       	+= asus620_ts.o
#obj-$(CONFIG_A620_BUTTONS)      += asus620_buttons.o
#obj-$(CONFIG_A620_PCMCIA)       += asus620_pcmcia.o
#obj-$(CONFIG_A620_FLASHFAKE)    += asus620_flashfake.o
