# Asus 620 Makefile

#CFLAGS += -Idrivers/pcmcia

obj-$(CONFIG_MACH_A620)		+= asus620.o asus620_gpo.o a620_leds.o asus620_ts.o
# a620_bt_power.o

obj-$(CONFIG_A620_DOC)    	+=  diskonchip.o inftl_ro.o
